---
title: "1.R"
output: html_document
date: "2024-07-01"
---


## R Markdown
```{r}
#1
Iowa.df<-read.csv("Iowa.csv",header=T)
results <- list(dim(Iowa.df), colnames(Iowa.df), Iowa.df[5, 7], Iowa.df[2, ])  
for (res in results) {  
  print(res)  
}  

```
```{r}
#2.a
vector1 <- c("5", "12", "7", "32")
commands <- c(  
  "max(vector1)",
  "sort(vector1)",
  "sum(vector1)"  
)


for (cmd in commands) {  
    result <- tryCatch({  
        eval(parse(text = cmd))  
    }, error = function(e) {  
        message(paste("Error:", e))  
        return(NULL)  
    })  
      
    if (!is.null(result)) {  
        print(result)  
    }  
}
```

```{r}
#2.b
vector2 <- c("5",7,12)
dataframe3 <- data.frame(z1="5",z2=7,z3=12)
list4 <- list(z1="6", z2=42, z3="49", z4=126)
commands <- c(
  "vector2[2] + vector2[3]",
  "dataframe3[1,2] + dataframe3[1,3]",
  "list4[[2]]+list4[[4]]",
  "list4[2]+list4[4]"
)
for (cmd in commands) {  
    result <- tryCatch({  
        eval(parse(text = cmd))  
    }, error = function(e) {  
        message(paste("Error:", e))  
        return(NULL)  
    })  
      
    if (!is.null(result)) {  
        print(result)  
    }  
}  
```
```{r}
#第二行存在问题。虽然这段代码没有报错，但它也不能得到正确的结果。在数据框中，列被存储为因子型数据，而不是作为数字型数据。因此，需要先将列转换为数字，然后再进行运算。
# list4[[2]]` 和 `list4[[4]]` 返回的是向量元素,而`list4[2]`和`list4[4]`返回的是元素所在位置的列表
```



```{r}
#3.a
sequence_1_to_10000_by_372 <- seq(1, 10000, by = 372)
sequence_1_to_10000_length_50 <- seq(1, 10000, length.out = 50)
print(sequence_1_to_10000_by_372)
print(sequence_1_to_10000_length_50)
```
#3.b
#rep()`函数在R中用于重复一个向量若干次。`rep(1:3, times=3)`和`rep(1:3, each=3)`的区别在于重复的方式：
#rep(1:3, times=3)`: 这将整个序列`1:3`重复三次。因此，结果向量将如下所示：1 2 3 1 2 3 1 2 3。
#rep(1:3, each=3)`: 这将每个`1:3`中的元素重复三次，然后再转到下一个元素。因此，结果向量将如下所示：1 1 1 2 2 2 3 3 3。

```{r}
#MB.Ch1.2
# 加载DAAG包  
library(DAAG)  
  
# 查看orings数据集  
data(orings)  
head(orings)  
  
# 从数据集中提取所需的行  
selected_rows <- orings[c(1, 2, 4, 11, 13, 18), ]  
  
# 创建新的数据框架  
selected_df <- data.frame(selected_rows)  
  
# 绘制选定行的温度图表  
plot(selected_df$Temperature, xlab = "Observation", ylab = "Temperature",   
     main = "Temperature at Selected Observations") 

# 使用lines函数连接点  
lines(selected_df$Temperature, type = "o", col = "blue") 
```

```{r}
#MB.Ch1.4
# 加载 DAAG 包  
library(DAAG)  
  
# 查看 ais 数据集  
data(ais)  
str(ais)  
  
# 检查缺失数值  
colSums(is.na(ais))  
  
# 创建一个表格，显示每种运动项目男女运动员的数量  
table(ais$sex, ais$sport)  
  
# 识别在两性人数上出现明显失衡的运动项目  
sport_table <- table(ais$sex, ais$sport)  
sex_ratio <- sport_table[1,] / sport_table[2,]  
sex_ratio[sex_ratio > 2 | sex_ratio < 0.5]  
```
```{r}
#MB.Ch1.6
# 创建数据帧  
Manitoba.lakes <- data.frame(  
  elevation = c(217, 254, 248, 254, 253, 227, 178, 207, 217),  
  area = c(24387, 5374, 4624, 2247, 1353, 1223, 1151, 755, 657)  
)  
  
# 使用row.names函数指定湖泊名称  
row.names(Manitoba.lakes) <- c("Winnipeg", "Winnipegosis", "Manitoba", "SouthernIndian", "Cedar", "Island", "Gods", "Cross", "Playgreen")  
  
# 显示数据框  
Manitoba.lakes  

attach(Manitoba.lakes)
plot(log2(area) ~ elevation, pch=16, xlim=c(170,280))
# NB: Doubling the area increases log2(area) by 1.0
text(log2(area) ~ elevation, labels=row.names(Manitoba.lakes), pos=4)
text(log2(area) ~ elevation, labels=area, pos=2)
title("Manitoba's Largest Lakes")
#点上的标签显示了马尼托巴省的湖泊名称和对应面积。
#y轴标签显示了湖泊面积（以平方公里为单位）的以2为底的对数。由于y轴是对数刻度，每向上移动一步代表湖泊面积翻倍。例如，如果一个点在y轴上比另一个点高出一个单位，这意味着对应的湖泊面积大约是另一个湖泊的两倍。
plot(area ~ elevation, pch=16, xlim=c(170,280), ylog=T)
text(area ~ elevation, labels=row.names(Manitoba.lakes), pos=4, ylog=T)
text(area ~ elevation, labels=area, pos=2, ylog=T)
title("Manitoba's Largest Lakes")
```

```{r}
#MB.Ch1.7
dotchart(log2(area))
```

```{r}
#MB.Ch1.8
lower_bound_area <- sum(Manitoba.lakes$area)  
lower_bound_area  
```

